DROP TABLE ROLE;
DROP TABLE XUsers;
DROP TABLE ADDRESS;
DROP TABLE RETAILER;
DROP TABLE CUSTOMER;
DROP TABLE OPERATOR;

DROP SEQUENCE USERS_SEQUENCE;

SELECT * FROM ROLE;
SELECT * FROM USERS;

DELETE FROM USERS;