CREATE TABLE XUsers (
 	userId 		INTEGER 		PRIMARY KEY,
 	username	VARCHAR(20) 	NOT NULL,
 	pwd 		VARCHAR(20) 	NOT NULL,
 	roleId		INTEGER			NOT NULL
);

CREATE SEQUENCE XUsers_Sequences
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE
	NOCACHE
	NOCYCLE;
	
	
